name: Main Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        env:
          ORG_GRADLE_PROJECT_BUILD_NUMBER: ${{ github.run_number}}
        run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: Build Jar ${{ github.run_number}}
          path: build/libs/pipo-hse-*.jar
